[phases.setup]
nixPkgs = [
    "php82",
    "php82Extensions.intl",
    "php82Extensions.zip",
    "php82Extensions.pdo",
    "php82Extensions.pdo_mysql",
    "php82Extensions.bcmath",
    "php82Extensions.gd",
    "php82Extensions.mbstring",
    "php82Extensions.xml",
    "php82Extensions.curl",
    "php82Extensions.fileinfo",
    "nodejs_20",
    "npm-9"
]

[phases.build]
cmds = [
    "npm install",
    "npm run build",
    "composer install --optimize-autoloader --no-dev --no-interaction --no-progress"
]

[start]
cmd = "php artisan migrate --force && php artisan storage:link && php artisan config:cache && php artisan route:cache && php artisan view:cache && heroku-php-apache2 public/"
